# Generated by Django 4.2.30 on 2026-07-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending Verification', max_length=50),
        ),
    ]
