# Generated by Django 4.2.30 on 2026-07-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.FloatField(default=0.0),
        ),
    ]
