# Generated by Django 4.2.30 on 2026-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
